services:
  vite-app:
    image: node:23 
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev --host"

  express-app:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend:/app  
      - /app/node_modules 
    ports:
      - "3000:3000"
    command: sh -c "npm install && nodemon index.js"

  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    ports:
      - "5432:5432" 

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  db_data:
